config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  # Daynamic Errors Pages
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  root 'documents#index'
  get '/sign_up', to: redirect('/')
  devise_for :users, :controllers => { :registrations => 'registrations', sessions: 'sessions', invitations: 'invitations'}, :path_names => {:sign_in => 'login', :sign_out => 'logout', edit: 'account', password: 'password', confirmation: 'confirmation'}, path: ''
  # Courses
  get ':id', to: 'courses#show', as: 'course', constraints: {id: /\w{2,4}\d{2,4}/}
  post 'load_more', to: 'courses#load_more', as: 'load_more'
  post 'search', to: 'courses#search', as: 'search'
  get ':id/:element_type.json', to: 'courses#get_course_document_type', as: 'get_course_document_type', constraints: {id: /\w{2,4}\d{2,4}/, element_type: /examform|notebook|summary|book/}
  get ':id/:document_id/show', to: 'courses#show_document', as: 'course_show_document', constraints: {id: /\w{2,4}\d{2,4}/, document_id: /\d+/}
  # Attachments
  resources :attachments, only: [:create, :new, :index]
  # Documents
  resources :documents, only: [:show, :index], constraints: {id: /\d+/} do
    member do
      get :download
    end
  end
  get '/go/:id', to: 'documents#short_link', as: 'document_short_link', constraints: {id: /\d+/}
  get '/add/:element_type', to: 'documents#new', as: 'new_document', constraints: {element_type: /examform|notebook|summary|book/}
  post '/documents', to: 'documents#create', as: 'create_document'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :registerable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :invitable
  has_many :documents
	extend FriendlyId
	friendly_id :username, use: [:slugged, :finders]
	validates_presence_of :first_name, :last_name, :username
	def full_name
		"#{self.first_name} #{self.last_name}" 
	end
	def owner?(document_id)
		if self == Document.find(document_id).user
			return true
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end
end

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "تسجيل الدخول", new_session_path(resource_name) %><br />
<% end -%>



<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "نسيت كلمة المرور؟", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "لم تستلم بريد تأكيد الحساب؟", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "لم تستلم بريد فك قفل الحساب؟", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "تسخيل الدخول بـ #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>