config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  # Daynamic Errors Pages
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  root 'documents#index'
  get '/sign_up', to: redirect('/')
  devise_for :users, :controllers => { :registrations => 'registrations', sessions: 'sessions', invitations: 'invitations'}, :path_names => {:sign_in => 'login', :sign_out => 'logout', edit: 'account', password: 'password', confirmation: 'confirmation'}, path: ''
  # Courses
  get ':id', to: 'courses#show', as: 'course', constraints: {id: /\w{2,4}\d{2,4}/}
  post 'load_more', to: 'courses#load_more', as: 'load_more'
  post 'search', to: 'courses#search', as: 'search'
  get ':id/:element_type.json', to: 'courses#get_course_document_type', as: 'get_course_document_type', constraints: {id: /\w{2,4}\d{2,4}/, element_type: /examform|notebook|summary|book/}
  get ':id/:document_id/show', to: 'courses#show_document', as: 'course_show_document', constraints: {id: /\w{2,4}\d{2,4}/, document_id: /\d+/}
  # Attachments
  resources :attachments, only: [:create, :new, :index]
  # Documents
  resources :documents, only: [:show, :index], constraints: {id: /\d+/} do
    member do
      get :download
    end
  end
  get '/go/:id', to: 'documents#short_link', as: 'document_short_link', constraints: {id: /\d+/}
  get '/add/:element_type', to: 'documents#new', as: 'new_document', constraints: {element_type: /examform|notebook|summary|book/}
  post '/documents', to: 'documents#create', as: 'create_document'
end

app/models/document.rb
class Document < ActiveRecord::Base
	include PublicActivity::Common
	include ActiveModel::ForbiddenAttributesProtection
	before_destroy :destory_element
	# Association
	belongs_to :attachment, dependent: :destroy
	belongs_to :user
	belongs_to :course, counter_cache: true
	belongs_to :examform, foreign_key: "element_id"
	belongs_to :notebook, foreign_key: "element_id"
	belongs_to :book, foreign_key: "element_id"
	belongs_to :summary, foreign_key: "element_id"
	# Accepts Nested Attribute
	accepts_nested_attributes_for :examform, :notebook, :book, :summary
	# Validate
	validates :attachment_id, :course_id, :element_type, :user_id, presence: true
	validates :attachment_id, uniqueness: true
	validates :element_type, inclusion: {in: %w{ examform notebook book summary }, message: "%{value} ليست قيمة صحيحة لنوع الملف"}
	# Get Document Element Object
	def element
		(self.element_type).classify.constantize.find(self.element_id)
	end
	def destory_element
		self.element.destroy
	end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_document, only: [:show, :download, :short_link]
  def index
  	@documents = Document.all
  end

  def show

  end

  def new
  	@document = Document.new
    if params[:element_type] == "examform"
      @examform = @document.build_examform
    elsif params[:element_type] == "notebook"
      @notebook = @document.build_notebook
    elsif params[:element_type] == "summary"
      @summary = @document.build_summary
    elsif params[:element_type] == "book"
      @book = @document.build_book
    end
    render template: "/documents/new/#{params[:element_type]}"
  end
  def create
  	@document = current_user.documents.create(document_params)
    if @document.save
      Attachment.find(@document.attachment_id).update_attribute(:used, true)
      redirect_to course_path(Course.friendly.find(@document.course_id))
      flash[:success] = 'تم حفط الملف بنجاح.'
    else
      redirect_to new_document_path(@document.element_type)
      flash[:error] = "حدث خطأ أثناء حفظ الملف الرجاء المحاولة مرة اخرى. في حال إستمرار الخطأ الرجاء التواصل معنا"
    end
  end
  def download
    @document.increment!(:download_count)
    redirect_to @document.attachment.file.url
  end
  def short_link
    @course = @document.course
    redirect_to course_show_document_path(@course, @document)
  end
  private
  def set_document
    @document = Document.find(params[:id])
  end
  def document_params
    params.require(:document).permit(:user_id, :course_id, :attachment_id, :element_type,
      examform_attributes: [:fall_id, :examtype_id, :semester_id],
      notebook_attributes: [:semester_id, :student_name, :teacher_name, examtype_ids: []],
      book_attributes: [:title],
      summary_attributes: [:student_name, :description, examtype_ids: []])
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
	def document_type_count(type)
		Document.where(element_type: type, course_id: Course.find(params[:id]||params[:course_id])).count
	end
end

app/views/documents/_document.html.erb
<% if document.element_type == 'examform' %>
  <tr id="document-<%= "#{document.id}" %>">
    <td><%= image_tag document.attachment.file.cover_thumb, width: '50' %></td>
    <td><%= t "activerecord.attributes.examtype.examtype.#{document.element.examtype.examtype}" %></td>
    <td><%= t "activerecord.attributes.semester.semester.#{document.element.semester.semester}" %></td>
    <td><%= document.element.fall.fall %></td>
    <td>
      <%= link_to "تحميل/عرض", "#", class: "btn btn-info", data: {toggle: "modal", target: "#showDocumentInfo", id: "#{document.id}"}, id: "showDocument" %>
    </td>
  </tr>
<% elsif document.element_type == 'notebook' %>
    <tr id="document-<%= "#{document.id}" %>">
    <td><%= image_tag document.attachment.file.cover_thumb, width: '50' %></td>
    <td><%= document.element.examtypes.map {|type| t "activerecord.attributes.examtype.examtype.#{type}"}.join('، ') %></td>
    <td><%= t "activerecord.attributes.semester.semester.#{document.element.semester.semester}" %></td>
    <td><%= document.element.student_name %></td>
    <td><%= document.element.teacher_name %></td>
    <td>
      <%= link_to "تحميل/عرض", "#", class: "btn btn-info", data: {toggle: "modal", target: "#showDocumentInfo", id: "#{document.id}"}, id: "showDocument" %>
    </td>
  </tr>
<% elsif document.element_type == 'summary' %>
    <tr id="document-<%= "#{document.id}" %>">
    <td><%= image_tag document.attachment.file.cover_thumb, width: '50' %></td>
    <td><%= document.element.examtypes.map {|type| t "activerecord.attributes.examtype.examtype.#{type}"}.join('، ') %></td>
    <td><%= document.element.student_name %></td>
    <td>
      <%= link_to "تحميل/عرض", "#", class: "btn btn-info", data: {toggle: "modal", target: "#showDocumentInfo", id: "#{document.id}"}, id: "showDocument" %>
    </td>
  </tr>
<% elsif document.element_type == 'book' %>
    <tr id="document-<%= "#{document.id}" %>">
    <td><%= image_tag document.attachment.file.cover_thumb, width: '50' %></td>
    <td><%= document.element.title %></td>
    <td>
      <%= link_to "تحميل/عرض", "#", class: "btn btn-info", data: {toggle: "modal", target: "#showDocumentInfo", id: "#{document.id}"}, id: "showDocument" %>
    </td>
  </tr>
<% end %>

app/views/documents/_document_modal.html.erb
<div class="row">
	<div class="col-md-12 text-center">
		<%= image_tag @document.attachment.file.cover, class: "document-model-thumb", width: '100%' %>
	</div>
</div>
<hr />
<div class="row">
  <div class="col-md-12">
  <ul class="list-group">
    <li class="list-group-item active text-center"><h4>تفاصيل الملف</h4></li>
    <% if @document.element_type == 'notebook' %>
      <li class="list-group-item">نوع الإمتحان: <%= @document.element.examtypes.map {|type| t "activerecord.attributes.examtype.examtype.#{type}"}.join('، ') %></li>
      <li class="list-group-item">الفصل الدراسي: <%= t "activerecord.attributes.semester.semester.#{@document.element.semester.semester}" %></li>
      <li class="list-group-item">اسم الطالب: <%= @document.element.student_name %></li>
      <li class="list-group-item">اسم المدرس:<%= @document.element.teacher_name %></li>
    <% elsif @document.element_type == 'examform' %>
      <li class="list-group-item">نوع الإمتحان: <%= t "activerecord.attributes.examtype.examtype.#{@document.element.examtype.examtype}" %></li>
      <li class="list-group-item">الفصل الدراسي: <%= t "activerecord.attributes.semester.semester.#{@document.element.semester.semester}" %></li>
      <li class="list-group-item">سنة المحتوى: <%= t "activerecord.attributes.fall.fall.#{@document.element.fall.fall}" %></li>
    <% elsif @document.element_type == 'book' %>
      <li class="list-group-item">العنوان: <%= @document.element.title %></li>
    <% elsif @document.element_type == 'summary' %>
      <li class="list-group-item">نوع الإمتحان: <%= @document.element.examtypes.map {|type| t "activerecord.attributes.examtype.examtype.#{type}"}.join('، ') %></li>
      <li class="list-group-item">اسم الطالب: <%= @document.element.student_name %></li>
      <li class="list-group-item">تفاصيل اضافية: <%= @document.element.description %></li>
    <% end %>
      <li class="list-group-item">بواسطة: <%= @document.user.full_name %></li>
      <% if current_user != nil %>
        <% if current_user.owner?(@document) || current_user.admin? %>
          <li class="list-group-item">عدد التحميلات: <%= @document.download_count %></li>
        <% end %>
      <% end %>
          <li class="list-group-item">
          رابط مختصر: 
          <div class="input-group">
            <input type="text" class="form-control ltr" onClick="this.select();" aria-describedby="sizing-addon2" value="<%= document_short_link_url(@document) %>">
            <span class="input-group-addon" id="sizing-addon2"><%= fa_icon 'share-alt' %></span>
          </div>
      </li>
  </ul>
  </div>
  <div class="col-md-12 text-center">
    <%= link_to download_document_path(@document), class: 'btn btn-success btn-lg', target: '_blank' do
      %>
      <span><%= fa_icon 'download' %> تحميل</span>
    <% end %>
  </div>
</div>

app/views/documents/_table_header.html.erb
<thead>
<% if params[:element_type] == 'examform'%>
  <tr>
    <th>صورة مصغرة</th>
    <th>نوع الامتحان</th>
    <th>الفصل الدراسي</th>
    <th>سنة المحتوى</th>
    <th>تفاصيل</th>
  </tr>
<% elsif params[:element_type] == 'notebook' %>
  <tr>
    <th>صورة مصغرة</th>
    <th>نوع الامتحان</th>
    <th>الفصل الدراسي</th>
    <th>اسم الطالب</th>
    <th>اسم المدرس</th>
    <th>تفاصيل</th>
  </tr>
<% elsif params[:element_type] == 'summary' %>
  <tr>
    <th>صورة مصغرة</th>
    <th>نوع الامتحان</th>
    <th>اسم الطالب</th>
    <th>تفاصيل</th>
  </tr>
<% elsif params[:element_type] == 'book' %>
  <tr>
    <th>صورة مصغرة</th>
    <th>عنوان الكتاب</th>
    <th>تفاصيل</th>
  </tr>
<% end %>
</thead>
<tbody>
</tbody>

app/views/documents/index.html.erb
<div class="search-jumbotron jumbotron clear">
  <div class="home-container">
    <div class="row">
        <div class="col-md-12">
          <%= image_tag 'logo.png', class: 'img-responsive center-block' %>
        </div>
        <div class="col-md-12 text-center">
          <h3 class="enter-course-text">ادخل اسم المساق او جزء منه</h3>
          <div class="search-box">
            <%= fa_icon 'search 3x', class: 'search-icon' %>
            <input class="ltr" id="courseSearch" type="text" placeholder="SE201, Software Modeling">
          </div>
        </div>
      </div>
  </div>
  <div class="credit">
    <span>برمجة وتصميم <a href="http://fb.com/anasjbers">أنس تّمام</a></span> |
    <span>الشعار مقدم من <a href="http://fb.com/moha619">محمد حموري</a></span>
  </div>
</div>

app/views/documents/new.html.erb
<%= title "رفع " + t("activerecord.attributes.document.element_type.#{params[:element_type]}") %>
<%= render template: new_document_path(params[:element_type]) %>

app/views/documents/new_as_content_type.html.erb
<%= render template: "documents/new/#{params[:content_type]}" %>