config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  # Daynamic Errors Pages
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  root 'documents#index'
  get '/sign_up', to: redirect('/')
  devise_for :users, :controllers => { :registrations => 'registrations', sessions: 'sessions', invitations: 'invitations'}, :path_names => {:sign_in => 'login', :sign_out => 'logout', edit: 'account', password: 'password', confirmation: 'confirmation'}, path: ''
  # Courses
  get ':id', to: 'courses#show', as: 'course', constraints: {id: /\w{2,4}\d{2,4}/}
  post 'load_more', to: 'courses#load_more', as: 'load_more'
  post 'search', to: 'courses#search', as: 'search'
  get ':id/:element_type.json', to: 'courses#get_course_document_type', as: 'get_course_document_type', constraints: {id: /\w{2,4}\d{2,4}/, element_type: /examform|notebook|summary|book/}
  get ':id/:document_id/show', to: 'courses#show_document', as: 'course_show_document', constraints: {id: /\w{2,4}\d{2,4}/, document_id: /\d+/}
  # Attachments
  resources :attachments, only: [:create, :new, :index]
  # Documents
  resources :documents, only: [:show, :index], constraints: {id: /\d+/} do
    member do
      get :download
    end
  end
  get '/go/:id', to: 'documents#short_link', as: 'document_short_link', constraints: {id: /\d+/}
  get '/add/:element_type', to: 'documents#new', as: 'new_document', constraints: {element_type: /examform|notebook|summary|book/}
  post '/documents', to: 'documents#create', as: 'create_document'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :get_course_document_type, :load_more, :show_document]
  def show
  	@documents = @course.documents.where(element_type: 'examform').order("download_count DESC").limit(10)
  end
  def get_course_document_type
    @documents = @course.documents.where(element_type: params[:element_type]).order("download_count DESC").limit(10)
  end
  def load_more
    @document_ids = params[:document_ids].map {|id| id.match(/[^-]+$/).to_s.to_i }
    @documents = @course.documents.where(element_type: params[:element_type]).where.not(id: @document_ids).order("download_count DESC").limit(10)
  end
  def search
    @results = Course.where("symbol like :search or name like :search", search: "%#{params[:query]}%").where("documents_count > 0")
  end
  def show_document
    @documents = @course.documents.where(element_type: 'examform').order("download_count DESC").limit(10)
    @document = Document.find(params[:document_id])
    respond_to do |format|
      format.html {render action: :show}
    end
  end
  private
  def set_course
    @course = Course.find(params[:id])
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/show.html.erb
<%= title "#{params[:course_id]|| params[:id]}".upcase %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-info">
        <p class="text-center">يحتوي مساق <strong><%= @course.symbol %></strong> على <strong><%= @course.documents_count %></strong> ملف</p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3 col-xs-12 col-sm-3 sidebar">
        <ul class="nav nav-sidebar">
            <% type_list.each do |name, value|
              %>
              <li class="dropdown">
                <%= link_to get_course_document_type_path(@course.slug, value), data: {toggle: "tab", target: value} do
                  %>
                    <%= name %>
                    <span class="badge pull-left"><%= document_type_count(value) %></span>
                <% end %>
              </li >
            <% end %>
        </ul>
    </div>
    <div class="col-xs-12 col-md-9 col-sm-9 table-col-content">
      <table class="table table-hover" id="documents-table">
        <thead>
          <tr>
            <th>صورة مصغرة</th>
            <th>نوع الامتحان</th>
            <th>الفصل الدراسي</th>
            <th>سنة المحتوى</th>
            <th>عرض</th>
          </tr>
        </thead>
          <%= render(@documents) %>
      </table>
        <div class="table-loader"><div class="fa fa-spinner fa-spin fa-10x"></div></div>
        <div class="loadmore-loader"><div class="fa fa-spinner fa-spin fa-2x"></div></div>
      <hr>
      <%= content_tag :div, class: 'row' do
        %>
        <%= content_tag :div, id: 'load-more', class: 'text-center' do
          %>
          <%= hidden_field_tag :course, "#{params[:id]}" %>
          <%= hidden_field_tag :element_type, 'examform' %>
          <input type="button" id="loadmore-btn" value="المزيد..." class="btn btn-default ">
        <% end %>
      <% end %>
    </div>
  </div>
  <%= render 'showDocumentModal' %>