config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  # Daynamic Errors Pages
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  root 'documents#index'
  get '/sign_up', to: redirect('/')
  devise_for :users, :controllers => { :registrations => 'registrations', sessions: 'sessions', invitations: 'invitations'}, :path_names => {:sign_in => 'login', :sign_out => 'logout', edit: 'account', password: 'password', confirmation: 'confirmation'}, path: ''
  # Courses
  get ':id', to: 'courses#show', as: 'course', constraints: {id: /\w{2,4}\d{2,4}/}
  post 'load_more', to: 'courses#load_more', as: 'load_more'
  post 'search', to: 'courses#search', as: 'search'
  get ':id/:element_type.json', to: 'courses#get_course_document_type', as: 'get_course_document_type', constraints: {id: /\w{2,4}\d{2,4}/, element_type: /examform|notebook|summary|book/}
  get ':id/:document_id/show', to: 'courses#show_document', as: 'course_show_document', constraints: {id: /\w{2,4}\d{2,4}/, document_id: /\d+/}
  # Attachments
  resources :attachments, only: [:create, :new, :index]
  # Documents
  resources :documents, only: [:show, :index], constraints: {id: /\d+/} do
    member do
      get :download
    end
  end
  get '/go/:id', to: 'documents#short_link', as: 'document_short_link', constraints: {id: /\d+/}
  get '/add/:element_type', to: 'documents#new', as: 'new_document', constraints: {element_type: /examform|notebook|summary|book/}
  post '/documents', to: 'documents#create', as: 'create_document'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :registerable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :invitable
  has_many :documents
	extend FriendlyId
	friendly_id :username, use: [:slugged, :finders]
	validates_presence_of :first_name, :last_name, :username
	def full_name
		"#{self.first_name} #{self.last_name}" 
	end
	def owner?(document_id)
		if self == Document.find(document_id).user
			return true
		end
	end
end

app/controllers/invitations_controller.rb
class InvitationsController < Devise::InvitationsController
  before_action :is_admin?, only: [:new, :create]
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end
end

app/views/users/invitations/edit.html.erb
<h2><%= t 'devise.invitations.edit.header' %></h2>

<%= simple_form_for resource, as: resource_name, url: invitation_path(resource_name), html: { method: :put } do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token %>
  
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  
  <%= f.button :submit, t("devise.invitations.edit.submit_button") %>
<% end %>

app/views/users/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= simple_form_for resource, as: resource_name, url: invitation_path(resource_name), html: { method: :post} do |f| %>
  <%= devise_error_messages! %>

<% resource.class.invite_key_fields.each do |field| -%>
  <%= f.input field %>
<% end -%>

<%= f.button :submit, t("devise.invitations.new.submit_button") %>
<% end %>